```{=html}
<style>
body {
text-align: justify}
</style>
```
# **Course Schedule**

Detailed schedule information with all asynchronous materials, assignment instructions and due dates is provided on Google Classroom.

\

+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| Session   | Tutorials to Review | Homework Due             | Async Materials (to be completed PRIOR tosessions) | Challenge (submit before session - reviewed in session) |
+===========+=====================+==========================+====================================================+=========================================================+
| 09/14/22  | Tutorial 1 - 5      | \                        | Data import                                        | 1: Challenge 1 Read data + HW1 setup github             |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 09/21/22  | Tutorial 7&9        | \                        | Group and Summarize                                | 2: Summary Statistics                                   |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 09/28/22  | \                   | \                        | Tidy Data                                          | 3: Read + pivot data                                    |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 10/05/22  | \                   | \                        | Data wrangling and transformation                  | 4: Mutate with lubridate and stringr                    |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 10/12/22  | \                   | HW2                      | \                                                  | HW2                                                     |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 10/19/22  | Tutorial  6&8       | \                        | Visualizing statistics                             | Univariate graph, Bivariate graph                       |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 10/26/22  | \                   | \                        | Visualizing time and groups                        | Graph over time, stacked bar chart                      |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 11/02/22  | \                   | \                        | Customizing ggplot                                 | Axis Labels, facets                                     |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 11/09/22  | \                   | \                        | Joins                                              | Joins                                                   |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 11/16/22  | \                   | HW3                      | \                                                  | HW3                                                     |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 11/23/22  | \                   | \                        | Creating your own Functions                        | Create a function                                       |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 11/30/22  | \                   | \                        | NO CLASS                                           | \                                                       |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 12/07/22  | \                   | \                        | purrr and map                                      | purrr                                                   |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| \         | \                   | \                        | Intro to Python                                    | optional                                                |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+
| 12/15/22  | \                   | Final Project Due Dec 18 | NO CLASS                                           | \                                                       |
+-----------+---------------------+--------------------------+----------------------------------------------------+---------------------------------------------------------+

\
