{
  "hash": "d20eb42097fa4e2e7f8c4fe184fd0a0a",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2\"\nauthor: \"Priya Marla\"\ndescription: \"Data wrangling: using group() and summarise()\"\ndate: \"12/27/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_2\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a data set, and describe the data using both words and any supporting information (e.g., tables, etc)\n2)  provide summary statistics for different interesting groups within the data, and interpret those statistics\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, available in the `posts/_data` folder, using the correct R package and command.\n\n-   railroad\\*.csv or StateCounty2012.xlsx ⭐\n-   FAOstat\\*.csv ⭐⭐⭐\n-   hotel_bookings ⭐⭐⭐⭐\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#loading the data from posts/_data folder\nrailroad <- read_csv(\"_data/railroad_2012_clean_county.csv\")\n#executed dim to know the dimentions i.e number of rows and columns of the dataset\ndim(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n:::\n\n\nAdd any comments or documentation as needed. More challenging data may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#executed colnames to get the column names in the dataset\ncolnames(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n\n```{.r .cell-code}\n#executed head to get the first 5 rows of the dataset\nhead(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               total_employees\n  <chr> <chr>                          <dbl>\n1 AE    APO                                2\n2 AK    ANCHORAGE                          7\n3 AK    FAIRBANKS NORTH STAR               2\n4 AK    JUNEAU                             3\n5 AK    MATANUSKA-SUSITNA                  2\n6 AK    SITKA                              1\n```\n:::\n\n```{.r .cell-code}\n#getting the distinct number of states and counties in the dataset\nrailroad%>%\n  select(state)%>%\n  n_distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 53\n```\n:::\n\n```{.r .cell-code}\nrailroad%>%\n  select(county)%>%\n  n_distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1709\n```\n:::\n\n```{.r .cell-code}\n#maximum of total employees in the dataset\nmax_count <- summarise(railroad, max(total_employees))\nmax_count\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `max(total_employees)`\n                   <dbl>\n1                   8207\n```\n:::\n\n```{.r .cell-code}\n#minimum of total employees in the dataset\nmin_count <- summarise(railroad, min(total_employees))\nmin_count\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `min(total_employees)`\n                   <dbl>\n1                      1\n```\n:::\n\n```{.r .cell-code}\n#mean of total employees in the dataset\nmean_count <- summarise(railroad, mean(total_employees))\nmean_count\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `mean(total_employees)`\n                    <dbl>\n1                    87.2\n```\n:::\n:::\n\nBy reading the data from \"railroad_2012_clean_county.csv\" dataset, I can see that this dataset describes the statistics of number of employees working in the different states and counties for the railroad in the year 2012. There are about 2930 rows and 3 columns where each row represents the total number of employees in each state and county. There a total of 53 states and 1709 counties. The maximum number of employee count recorded is 8207 and minimum count is 1. The average of total_employees in the entire dataset is 87.17816.\n\n\n## Provide Grouped Summary Statistics\n\nConduct some exploratory data analysis, using dplyr commands such as `group_by()`, `select()`, `filter()`, and `summarise()`. Find the central tendency (mean, median, mode) and dispersion (standard deviation, mix/max/quantile) for different subgroups within the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#total employees in all states and counties\nsummarise(railroad, sum(total_employees, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `sum(total_employees, na.rm = TRUE)`\n                                 <dbl>\n1                               255432\n```\n:::\n\n```{.r .cell-code}\n#total employees in county addison\nrailroad %>%\n  filter(county == \"ADDISON\") %>%\n  select_all() %>%\n  summarise(total_employees = sum(total_employees, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  total_employees\n            <dbl>\n1               8\n```\n:::\n\n```{.r .cell-code}\n#sum of total employees of each state\nrailroad %>%\n  group_by(state) %>%\n  select_all() %>%\n  summarise(sum_total_employees = sum(total_employees)) %>%\n  arrange(desc(sum_total_employees), .by_group=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state sum_total_employees\n   <chr>               <dbl>\n 1 TX                  19839\n 2 IL                  19131\n 3 NY                  17050\n 4 NE                  13176\n 5 CA                  13137\n 6 PA                  12769\n 7 OH                   9056\n 8 GA                   8605\n 9 IN                   8537\n10 MO                   8419\n# … with 43 more rows\n```\n:::\n\n```{.r .cell-code}\n#mean of total employees of each state\nrailroad %>%\n  group_by(state) %>%\n  select_all() %>%\n  summarise(mean_total_employees = mean(total_employees)) %>%\n  arrange(desc(mean_total_employees), .by_group=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state mean_total_employees\n   <chr>                <dbl>\n 1 DE                    498.\n 2 NJ                    397.\n 3 CT                    324 \n 4 MA                    282.\n 5 NY                    280.\n 6 DC                    279 \n 7 CA                    239.\n 8 AZ                    210.\n 9 PA                    196.\n10 MD                    196.\n# … with 43 more rows\n```\n:::\n\n```{.r .cell-code}\n#median of total employees of each state\nrailroad %>%\n  group_by(state) %>%\n  select_all() %>%\n  summarise(median_total_employees = median(total_employees))%>%\n  arrange(desc(median_total_employees), .by_group=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state median_total_employees\n   <chr>                  <dbl>\n 1 NJ                      296 \n 2 DC                      279 \n 3 MA                      271 \n 4 DE                      158 \n 5 CT                      125 \n 6 MD                      108.\n 7 AZ                       94 \n 8 PA                       85 \n 9 NY                       71 \n10 CA                       61 \n# … with 43 more rows\n```\n:::\n\n```{.r .cell-code}\n#min of total employees of each state\nrailroad %>%\n  group_by(state) %>%\n  select_all() %>%\n  summarise(min_total_employees = min(total_employees)) %>%\n  arrange(desc(min_total_employees), .by_group=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state min_total_employees\n   <chr>               <dbl>\n 1 DC                    279\n 2 DE                     62\n 3 MA                     44\n 4 CT                     26\n 5 NJ                     19\n 6 RI                      8\n 7 NY                      5\n 8 AZ                      3\n 9 IN                      3\n10 OH                      3\n# … with 43 more rows\n```\n:::\n\n```{.r .cell-code}\n#max of total employees of each state\nrailroad %>%\n  group_by(state) %>%\n  select_all() %>%\n  summarise(max_total_employees = max(total_employees)) %>%\n  arrange(desc(max_total_employees), .by_group=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 53 × 2\n   state max_total_employees\n   <chr>               <dbl>\n 1 IL                   8207\n 2 TX                   4235\n 3 NE                   3797\n 4 NY                   3685\n 5 VA                   3249\n 6 FL                   3073\n 7 CA                   2888\n 8 MO                   2055\n 9 IN                   1999\n10 PA                   1649\n# … with 43 more rows\n```\n:::\n:::\n\n\n### Explain and Interpret\n\nBe sure to explain why you choose a specific group. Comment on the interpretation of any interesting differences between groups that you uncover. This section can be integrated with the exploratory data analysis, just be sure it is included.\n\nData Analysis has been performed on the column state. Here each row represents a state and there are 53 unique states in the data set. State \"TX\" has recorded highest number of employees i.e 19839 and least is \"AP\" with 1 employee. Even though \"TX\" recorded highest employee count, the minimum number of employee in one of the counties is 1 and highest is 4235 making the average as 89.76. Highest average of employees are recorded in state \"DE\" and least in \"AP\". The minimum employees in most of the states in a particular county is 1 which is way less than state mean. \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}