{
  "hash": "c7be420e0dd13321400bc539c5fbb78f",
  "result": {
    "markdown": "---\ntitle: \"Challenge 1\"\nauthor: \"Priya MArla\"\ndescription: \"Reading in data and creating a post\"\ndate: \"12/26/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge_1\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n## Challenge Overview\n\nToday's challenge is to\n\n1)  read in a dataset, and\n\n2)  describe the dataset using both words and any supporting information (e.g., tables, etc)\n\n## Read in the Data\n\nRead in one (or more) of the following data sets, using the correct R package and command.\n\n-   railroad_2012_clean_county.csv ⭐\n-   birds.csv ⭐⭐\n-   FAOstat\\*.csv ⭐⭐\n-   wild_bird_data.xlsx ⭐⭐⭐\n-   StateCounty2012.xlsx ⭐⭐⭐⭐\n\nFind the `_data` folder, located inside the `posts` folder. Then you can read in the data, using either one of the `readr` standard tidy read commands, or a specialized package such as `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#loading the data from posts/_data folder\nrailroad <- read_csv(\"_data/railroad_2012_clean_county.csv\")\n#executed dim to know the dimentions i.e number of rows and columns of the dataset\ndim(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2930    3\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#executed colnames to get the column names in the dataset\ncolnames(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"state\"           \"county\"          \"total_employees\"\n```\n:::\n\n```{.r .cell-code}\n#executed head to get the first 5 rows of the dataset\nhead(railroad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               total_employees\n  <chr> <chr>                          <dbl>\n1 AE    APO                                2\n2 AK    ANCHORAGE                          7\n3 AK    FAIRBANKS NORTH STAR               2\n4 AK    JUNEAU                             3\n5 AK    MATANUSKA-SUSITNA                  2\n6 AK    SITKA                              1\n```\n:::\n:::\n\n\nAdd any comments or documentation as needed. More challenging data sets may require additional code chunks and documentation.\n\n## Describe the data\n\nUsing a combination of words and results of R commands, can you provide a high level description of the data? Describe as efficiently as possible where/how the data was (likely) gathered, indicate the cases and variables (both the interpretation and any details you deem useful to the reader to fully understand your chosen data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#getting the distinct number of states and counties in the dataset\nrailroad%>%\n  select(state)%>%\n  n_distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 53\n```\n:::\n\n```{.r .cell-code}\nrailroad%>%\n  select(county)%>%\n  n_distinct(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1709\n```\n:::\n\n```{.r .cell-code}\n#maximum of total employees in the dataset\nmax_count <- summarise(railroad, max(total_employees))\nmax_count\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `max(total_employees)`\n                   <dbl>\n1                   8207\n```\n:::\n\n```{.r .cell-code}\n#minimum of total employees in the dataset\nmin_count <- summarise(railroad, min(total_employees))\nmin_count\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `min(total_employees)`\n                   <dbl>\n1                      1\n```\n:::\n\n```{.r .cell-code}\n#mean of total employees in the dataset\nmean_count <- summarise(railroad, mean(total_employees))\nmean_count\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  `mean(total_employees)`\n                    <dbl>\n1                    87.2\n```\n:::\n:::\n\nBy reading the data from \"railroad_2012_clean_county.csv\" dataset, I can see that this dataset describes the statistics of number of employees working in the different states and counties for the railroad in the year 2012. There are about 2930 rows and 3 columns where each row represents the total number of employees in each state and county. There a total of 53 states and 1709 counties. The maximum number of employee count recorded is 8207 and minimum count is 1. The average of total_employees in the entire dataset is 87.17816.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}