{
  "hash": "b1cd105b6adb6e2d5ba5cc1b41e4b8e3",
  "result": {
    "markdown": "---\ntitle: \"Challenge 2: Data Wrangling\"\nauthor: \"Surya Praneeth Reddy Chirasani\"\ndescription: \"Data wrangling: summary statistics of dataset\"\ndate: \"01/06/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - challenge2\n  - dataset\n  - Data Wrangling\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(\"readxl\")\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_employment <-read_excel(\"_data/StateCounty2012.xls\",\n                     skip = 4,\n                     col_names= c(\"state\", \"2nd_column\",  \"county\",\n                                  \"4th_column\", \"employees\"))%>%\n  select(!contains(\"column\"))%>%\n  filter(!str_detect(state, \"Total\"))\nhead(railroad_employment)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state county               employees\n  <chr> <chr>                    <dbl>\n1 AE    APO                          2\n2 AK    ANCHORAGE                    7\n3 AK    FAIRBANKS NORTH STAR         2\n4 AK    JUNEAU                       3\n5 AK    MATANUSKA-SUSITNA            2\n6 AK    SITKA                        1\n```\n:::\n:::\n\nThe dataset has some intial rows that are not relevant for analysis to form a dataframe which I have skipped and remaining rows can be explained in 3 columns with *State*, *county* and *employees*. Each row has information on total number of employees working in a particular state and a particular county in that county. I have deleted rows which has information of total number of employees in a given state, which is redundant and can be calculated by summary statistics analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_employment<-head(railroad_employment, -2)\ntail(railroad_employment)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state  county     employees\n  <chr>  <chr>          <dbl>\n1 WY     SUBLETTE           3\n2 WY     SWEETWATER       196\n3 WY     UINTA             49\n4 WY     WASHAKIE          10\n5 WY     WESTON            37\n6 CANADA <NA>             662\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_employment <- mutate(railroad_employment, county = ifelse(state==\"CANADA\", \"CANADA\", county))\ntail(railroad_employment)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  state  county     employees\n  <chr>  <chr>          <dbl>\n1 WY     SUBLETTE           3\n2 WY     SWEETWATER       196\n3 WY     UINTA             49\n4 WY     WASHAKIE          10\n5 WY     WESTON            37\n6 CANADA CANADA           662\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_employment %>% select(state, county) %>% summarise_all(list(~n_distinct(.)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  state county\n  <int>  <int>\n1    54   1710\n```\n:::\n:::\n\nThere are total of 54 states of which 50 are US states, 1 federal district(Washington DC), 2 military designation places and last one is Canada.\nTotal counties are 1710 including those of Canada and minitary designation places\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(railroad_employment[, \"employees\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 256094\n```\n:::\n:::\n\nTotal number of railway employees employed are 256094 which is about 0.08% of the total population of US(2011 Census Total population of 310 million)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrailroad_employment %>%\n  group_by(state) %>%\n  summarise(total_employees = sum(employees),\n            num_counties = n())%>%\n  arrange(desc(total_employees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 54 × 3\n   state total_employees num_counties\n   <chr>           <dbl>        <int>\n 1 TX              19839          221\n 2 IL              19131          103\n 3 NY              17050           61\n 4 NE              13176           89\n 5 CA              13137           55\n 6 PA              12769           65\n 7 OH               9056           88\n 8 GA               8605          152\n 9 IN               8537           92\n10 MO               8419          115\n# … with 44 more rows\n```\n:::\n:::\n\nThe top 5 states with highest employees are states which has geographically large area and large number of counties which makes sense since you need more employees to canter to the area and the population\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}