{
  "hash": "46e1646388e65bb60bedccd49da92cdc",
  "result": {
    "markdown": "---\ntitle: \"Homework 2\"\nauthor: \"Yoshita Varma\"\ndesription: \"Reading in and Desribing Data\"\ndate: \"01/20/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - hw2\n  - WDI.csv\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"dyplr\")\nlibrary(tidyverse)\nlibrary(dplyr)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Reading in and Describing Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nIndicators = read_csv(\"_data/WDI/Indicators.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 5656458 Columns: 6\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): CountryName, CountryCode, IndicatorName, IndicatorCode\ndbl (2): Year, Value\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nIndicators %>%\n  view()\n\nIndicators %>%\n  dim() \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5656458       6\n```\n:::\n\n```{.r .cell-code}\nIndicators %>% \n  colnames()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"CountryName\"   \"CountryCode\"   \"IndicatorName\" \"IndicatorCode\"\n[5] \"Year\"          \"Value\"        \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nIndicators %>%\n  distinct(CountryName) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 247 × 1\n   CountryName                              \n   <chr>                                    \n 1 Arab World                               \n 2 Caribbean small states                   \n 3 Central Europe and the Baltics           \n 4 East Asia & Pacific (all income levels)  \n 5 East Asia & Pacific (developing only)    \n 6 Euro area                                \n 7 Europe & Central Asia (all income levels)\n 8 Europe & Central Asia (developing only)  \n 9 European Union                           \n10 Fragile and conflict affected situations \n# … with 237 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nIndicators %>% \n  distinct(IndicatorName)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,344 × 1\n   IndicatorName                                                \n   <chr>                                                        \n 1 Adolescent fertility rate (births per 1,000 women ages 15-19)\n 2 Age dependency ratio (% of working-age population)           \n 3 Age dependency ratio, old (% of working-age population)      \n 4 Age dependency ratio, young (% of working-age population)    \n 5 Arms exports (SIPRI trend indicator values)                  \n 6 Arms imports (SIPRI trend indicator values)                  \n 7 Birth rate, crude (per 1,000 people)                         \n 8 CO2 emissions (kt)                                           \n 9 CO2 emissions (metric tons per capita)                       \n10 CO2 emissions from gaseous fuel consumption (% of total)     \n# … with 1,334 more rows\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nIndicators %>% \n  distinct(Year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 56 × 1\n    Year\n   <dbl>\n 1  1960\n 2  1961\n 3  1962\n 4  1963\n 5  1964\n 6  1965\n 7  1966\n 8  1967\n 9  1968\n10  1969\n# … with 46 more rows\n```\n:::\n:::\n\nI have used the World Development Indicators dataset to identify the factors contributing towards a country's development. Describes data for a period of 60 years(1960-2020) for 247 countries. Has 5.6 million rows with 1344 indicators. For the analysis, the World Development Indicators dataset was used. The data is a slightly modified version from the dataset that’s actually available from the World Bank, a group which provides a wide array of financial products. It’s an informative dataset containing factors which contribute to world development.\n\nDataset link - https://www.kaggle.com/datasets/kaggle/world-development-indicators\n\n\n## Tidying Data\n\nMost, if not all, of this data is already in a tidy format. All variables have their own respective columns and values within them, and all observations have their own rows. The data is very large, but that is because there are many different Countries to examine for various factors of the development. I faced many challenges with the dataset preparation. After this, cleaning and handling the dataset also took some modidications to csv file itself primarily because of its size.\n\nDataset cleaning and preparation - As the dataset had 5.6 million rows with 1344 indicators with any missing values. We had to handle multiple blank chunks of data and import this information from other sources while getting these csv files. \n\n\n## Narative/Analysis of the data\n\nThe following indicators will be our major area of research - \n\n- Life expectancy at birth, total (years)\n\n- Adjusted net national income (current US$)\n\n- Population, total\n\n- GDP per capita (constant 2005 US$)\n\n- Gross national expenditure (constant 2005 US$)\n\n- Merchandise exports (current US$)\n\n- Net official development assistance received (current US$)\n\n\n-Health expenditure per capita (current US$)\n\n-GDP per capita (current US$)\n\n-Government expenditure on education (% of GDP)\n\n-Prevalence of overweight in children, weight for height (% of children under 5)\n\n-Logistics performance index: Quality of trade and transport-related infrastructure\n\n-Research and development expenditure (% of GDP)\n\nI think everyone would be interested in their country's development. Especially to know how long their ancestors might have lived right?\nWhat if you get to visualize this data? Thats sounds interesting right. So yes we have picked up this interest as our research question. Here it is today we will be presenting a visualizaiton through which you can easily analy your country's development and also gauge the life expectancy’s trends. \n\n\n## Research Questions for Data\n\nMOTIVATION:Life expectancy in every country has been increasing since the 19th century. My hypothesis is that, one of main factors contributing to the life expectancy increase, has been advancements in technology and infrastructure. It will be interesting to validate this fact, with the help of the data correlation. Hence, to shed light on this in a more empirical way, I wanted to research various factors that might have driven this change. I shortlisted a few factors relating to technology and infrastructure and also some other miscellaneous health related factors that might have an impact on life expectancy in a country. \n\nRESEARCH QUESTIONS: Following question will be addressed using this dataset:\n\n1) Is life expectancy getting better for countries across the globe?\n\n2) Does a country's development and growth cause life expectancy to increase?\n\n3) What are the other major factors and how much impact these factors are contributing to the increase of country’s life expectancy?\n\nCountry’s development and growth are not directly measured as it is not part of this dataset. However, it is measured by combining a few indicators (from the dataset) which attribute a country's overall performance in advancement.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}